# Hands On - Live Coding Class : Python
## *Data Engineer Batch 11*
#### Made by **Mario Caesar** (https://linktr.ee/caesarmario_)

In [ ]:
if a == 0:
  print("something")
else:

# Live Coding Exercise

## 1. Log Transaksi: Total Belanja per User
**Topik**: Data Types & Structures (string, list, dict), looping

### Cerita
Kamu diberi log transaksi dalam bentuk list of strings dengan format: `user,produk,harga`. Hitung **total belanja per user** dan tentukan **top spender**.

### Contoh Input
```py
logs = [
    "ana,book,120.5",
    "budi,pen,10",
    "ana,bag,250",
    "cici,book,120.5",
    "budi,notebook,35.5",
]
```

### Contoh Output
```py
# dict total
{'ana': 370.5, 'budi': 45.5, 'cici': 120.5}

# top spender
('ana', 370.5)
```

### Hint
- `str.split(',')` untuk parsing
- `float()` untuk harga
- `dict.get(k, 0)` untuk akumulasi


In [1]:
logs = [
    "ana,book,120.5",
    "budi,pen,10",
    "ana,bag,250",
    "cici,book,120.5",
    "budi,notebook,35.5",
]

## Jawaban disini ##

total_per_user = {}
for i in logs :
  # print(i.split(','))
  user, product, price = i.split(',')
  print(user, product, price)
  float(price)
  total_per_user[user] =

SyntaxError: invalid syntax (4073604641.py, line 17)

## 2. Pandas: Ringkas Penjualan per Kategori & Filter Tanggal
Topik: DataFrame & Looping (pandas groupby, filter, sort)

### Cerita
Kamu punya data order e-commerce. Buat ringkasan **revenue per kategori** untuk bulan **2025-06** saja, urutkan dari revenue terbesar.

### Contoh Input
```py
import pandas as pd

df = pd.DataFrame({
    "order_id": [1,2,3,4,5,6],
    "order_date": pd.to_datetime([
        "2025-06-01","2025-06-10","2025-05-30",
        "2025-06-21","2025-06-25","2025-07-01"
    ]),
    "category": ["book","stationery","book","bag","book","bag"],
    "qty": [1,2,3,1,2,1],
    "price": [120.5,10.0,120.5,250.0,120.5,250.0]
})
```

### Contoh Output
```
   category  revenue
0      book    481.5
1       bag    250.0
2 stationery     20.0
```

### Hint
- Filter bulan: `df[df['order_date'].dt.month == 6]` dan `dt.year == 2025`
- Revenue = `qty * price`
- `groupby('category')['revenue'].sum().reset_index()`
- `sort_values('revenue', ascending=False)`


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "order_id": [1,2,3,4,5,6],
    "order_date": pd.to_datetime([
        "2025-06-01","2025-06-10","2025-05-30",
        "2025-06-21","2025-06-25","2025-07-01"
    ]),
    "category": ["book","stationery","book","bag","book","bag"],
    "qty": [1,2,3,1,2,1],
    "price": [120.5,10.0,120.5,250.0,120.5,250.0]
})

## Jawaban disini ##
juni = df[df['order_date'].dt.month == 6]
juni.head()
revenue = df['qty']*df['price']
# print(revenue)
df[revenue] = revenue
print(df)

   order_id order_date    category  qty  price  120.5  20.0  361.5  250.0  \
0         1 2025-06-01        book    1  120.5  120.5  20.0  361.5  250.0   
1         2 2025-06-10  stationery    2   10.0  120.5  20.0  361.5  250.0   
2         3 2025-05-30        book    3  120.5  120.5  20.0  361.5  250.0   
3         4 2025-06-21         bag    1  250.0  120.5  20.0  361.5  250.0   
4         5 2025-06-25        book    2  120.5  120.5  20.0  361.5  250.0   
5         6 2025-07-01         bag    1  250.0  120.5  20.0  361.5  250.0   

   241.0  
0  241.0  
1  241.0  
2  241.0  
3  241.0  
4  241.0  
5  241.0  


## 3. Diskon Dinamis per Kategori (Function + Lambda)
Topik: Function, Lambda, map/filter, list/dict

### Cerita
Buat fungsi `apply_discounts(items, rules)` yang menerima:
- `items`: list of dict seperti `{"sku": "A1", "category": "book", "price": 100}`
- `rules`: dict mapping kategori → **lambda** yang mengembalikan **persentase diskon (0–1)** atau nilai diskon.

Hitung **harga setelah diskon** per item, dan **total penghematan**.

### Contoh Input
```py
items = [
    {"sku": "B001", "category": "book", "price": 120.0},
    {"sku": "S010", "category": "stationery", "price": 20.0},
    {"sku": "B002", "category": "book", "price": 150.0},
    {"sku": "BAG1", "category": "bag", "price": 250.0},
]

# diskon: book 10%, stationery 20% jika price < 25, bag diskon flat 30
rules = {
    "book":       lambda item: 0.10 * item["price"],
    "stationery": lambda item: 0.20 * item["price"] if item["price"] < 25 else 0.0,
    "bag":        lambda item: 30.0
}
```

### Contoh Output
```
[
 {'sku': 'B001', 'category': 'book', 'price': 120.0, 'discount': 12.0, 'final_price': 108.0},
 {'sku': 'S010', 'category': 'stationery', 'price': 20.0,  'discount': 4.0,  'final_price': 16.0},
 {'sku': 'B002', 'category': 'book', 'price': 150.0, 'discount': 15.0, 'final_price': 135.0},
 {'sku': 'BAG1', 'category': 'bag', 'price': 250.0, 'discount': 30.0, 'final_price': 220.0}
]
total_saving = 61.0
```

### Hint
- Gunakan `rules.get(item['category'], default_lambda)`
- `map` atau list comprehension
- Hindari mutate input, buat dict baru per item (`{**item, 'discount': ..., 'final_price': ...}`)


In [ ]:
items = [
    {"sku": "B001", "category": "book", "price": 120.0},
    {"sku": "S010", "category": "stationery", "price": 20.0},
    {"sku": "B002", "category": "book", "price": 150.0},
    {"sku": "BAG1", "category": "bag", "price": 250.0},
]

rules = {
    "book":       lambda item: 0.10 * item["price"],
    "stationery": lambda item: 0.20 * item["price"] if item["price"] < 25 else 0.0,
    "bag":        lambda item: 30.0
}

def apply_discounts(items, rules):
    ## Jawaban disini ##



out, total_saving = apply_discounts(items, rules)
print(out)
print("total_saving =", total_saving)

## 4. Normalisasi Email & Hitung Pengguna Unik per Domain
Topik: String parsing, set, dict

### Cerita
Tim growth ingin menghitung jumlah pengguna unik berdasarkan **domain email**. Untuk Gmail, aturan uniknya khusus:
- **Gmail mengabaikan titik (.)** pada bagian lokal (sebelum @)
- **Bagian setelah tanda plus (+)** diabaikan (mis. ana+promo@gmail.com → ana@gmail.com).
- Untuk domain lain (yahoo, company, dll) **pakai apa adanya**.

Buat fungsi yang:
- Menormalisasi alamat email
- Menghitung **jumlah pengguna unik per domain**

### Contoh Input
```py
emails = [
    "ana.smith+promo@gmail.com",
    "anasmith@gmail.com",
    "budi@yahoo.com",
    "b.u.d.i@yahoo.com",
    "ops+test@company.com",
    "ops@company.com",
]
```

### Contoh Output
```
{
  'gmail.com': 1,       # 'ana.smith+promo' & 'anasmith' -> 'anasmith@gmail.com'
  'yahoo.com': 2,       # yahoo tidak pakai aturan gmail
  'company.com': 1      # 'ops+test' dan 'ops' dianggap sama? -> beda domain non-gmail => sama2 dihitung unik apa adanya
}
```
*) Catatan: Untuk non-gmail, abaikan aturan plus/dot → alamat dianggap apa adanya, sehingga ops+test@company.com dan ops@company.com adalah dua akun berbeda.

### Hint
- `email.split('@')`
- Untuk gmail: buang substring setelah `'+'` dan hapus `'.'` pada local-part
- Gunakan `set` untuk simpan alamat ter-normalisasi
- Hitung per domain dengan `dict`


In [ ]:
def normalize_emails(emails):
    ## Jawaban disini ##

# Test
emails = [
    "ana.smith+promo@gmail.com",
    "anasmith@gmail.com",
    "budi@yahoo.com",
    "b.u.d.i@yahoo.com",
    "ops+test@company.com",
    "ops@company.com",
]

print(normalize_emails(emails))

## 5. Join Data Pelanggan & Order: Revenue per Country (Q1 2025)
Topik: DataFrame merge, filter waktu, groupby, missing values

### Cerita
Ada dua tabel:
- **customers**: `customer_id, country`
- **orders**: `order_id, customer_id, order_date, amount`
Hitung total revenue per country untuk Q1 2025 (`Jan–Mar 2025`).
Tampilkan semua negara meskipun tidak ada order (revenue = 0).

### Contoh Input
```py
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1,2,3,4],
    "country": ["ID", "SG", "ID", "MY"]
})

orders = pd.DataFrame({
    "order_id":   [10,11,12,13,14,15],
    "customer_id":[1,2,1,3,2,2],
    "order_date": pd.to_datetime([
        "2025-01-05","2025-02-10","2024-12-30",
        "2025-03-21","2025-04-01","2025-01-20"
    ]),
    "amount":     [100,200,50,300,400,150]
})
```

### Contoh Output
```
  country  revenue
0      ID      400   # cust 1 (100) + cust 3 (300)
1      MY        0
2      SG      350   # cust 2 (200 + 150)
```

### Hint
- `pd.merge(customers, orders, on='customer_id', how='left')`
- Filter `order_date` di Q1 2025 (month in [1,2,3] & year = 2025)
- `fillna(0)` pada `amount`
- `groupby('country')['amount'].sum()`
- `sort_values('country')` (opsional)


In [ ]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [1,2,3,4],
    "country": ["ID", "SG", "ID", "MY"]
})

orders = pd.DataFrame({
    "order_id":   [10,11,12,13,14,15],
    "customer_id":[1,2,1,3,2,2],
    "order_date": pd.to_datetime([
        "2025-01-05","2025-02-10","2024-12-30",
        "2025-03-21","2025-04-01","2025-01-20"
    ]),
    "amount":     [100,200,50,300,400,150]
})

## Jawaban disini ##

## 6. OOP Basic: Kelas BankAccount
Topik: OOP dasar (class, atribut, method), validasi sederhana, list/looping

### Cerita
Buat class `BankAccount` yang mendukung:
- `deposit(amount)` menambah saldo
- `withdraw(amount)` mengurangi saldo (tidak boleh minus)
- `history(n=5)` menampilkan **n transaksi terakhir** (deposit/withdraw)
- `balance` properti untuk melihat saldo saat ini
Kemudian, dari daftar transaksi (list of dict), proses semua dan tampilkan **saldo akhir** serta **2 transaksi terakhir**.

### Contoh Input
```py
txs = [
    {"type": "deposit", "amount": 500},
    {"type": "withdraw", "amount": 120},
    {"type": "deposit", "amount": 200},
    {"type": "withdraw", "amount": 700},   # gagal (saldo tidak cukup)
    {"type": "withdraw", "amount": 100},
]
```

### Contoh Output
```py
Saldo akhir: 480
Last 2 tx: [{'type': 'withdraw', 'amount': 100}, {'type': 'deposit', 'amount': 200}]
```
*(Catatan urutan last 2 bisa dibalik tergantung implementasi; yang penting 2 transaksi terakhir yang berhasil.)*


### Hint
- Simpan `self._balance` dan `self._tx_log` (list)
- Validasi nominal `amount > 0`
- Jika withdraw melebihi saldo → tolak & jangan log sebagai sukses
- Bisa pakai `deque` (opsional), tapi list biasa cukup


In [ ]:
# Data Transaksi
txs = [
    {"type": "deposit", "amount": 500},
    {"type": "withdraw", "amount": 120},
    {"type": "deposit", "amount": 200},
    {"type": "withdraw", "amount": 700},   # gagal
    {"type": "withdraw", "amount": 100},
]

class BankAccount:
    ## Jawaban disini ##

## 7. Streaming Log dengan Generator (hemat memori)
Topik: Generator (yield), parsing string, perhitungan agregat

### Cerita
Kamu menerima file log yang sangat besar. Hitung berapa banyak baris `INFO`, `WARN`, dan `ERROR` **tanpa memuat seluruh data ke memori**. Gunakan **generator** agar baris diproses satu per satu.

### Contoh Input
```py
logs = [
    "2025-08-10 10:00:01 INFO User login",
    "2025-08-10 10:00:02 ERROR DB timeout",
    "2025-08-10 10:00:03 INFO Page view",
    "2025-08-10 10:00:04 WARN Slow query",
    "2025-08-10 10:00:05 ERROR Out of memory",
]
```

### Contoh Output
```py
{'INFO': 2, 'WARN': 1, 'ERROR': 2}
```

### Hint
- Buat generator `read_lines(data)` yang `yield` satu baris per iterasi
- Ambil **level** dari kolom ke-3 (`split()[2]`)
- Pakai dict biasa untuk menghitung


In [ ]:
def read_lines(seq):
     ## Jawaban disini ##

def count_levels(log_iter):
     ## Jawaban disini ##

logs = [
    "2025-08-10 10:00:01 INFO User login",
    "2025-08-10 10:00:02 ERROR DB timeout",
    "2025-08-10 10:00:03 INFO Page view",
    "2025-08-10 10:00:04 WARN Slow query",
    "2025-08-10 10:00:05 ERROR Out of memory",
]

print(count_levels(read_lines(logs)))

## 8. Pivot Penjualan per Region x Product (Q2 2025)
Topik: Pandas pivot/unstack, filter tanggal, grand total

### Cerita
Dari data penjualan, tampilkan **tabel pivot** `qty` per **region x product** untuk **Q2 2025** (April–Juni). Tampilkan 0 jika tidak ada penjualan, serta **tambahkan Grand Total** baris & kolom.

### Contoh Input
```py
import pandas as pd
df = pd.DataFrame({
    "date": pd.to_datetime([
        "2025-04-01","2025-04-02","2025-05-15","2025-06-10",
        "2025-03-30","2025-07-01"
    ]),
    "region": ["ID","SG","ID","MY","ID","SG"],
    "product":["A","A","B","A","A","B"],
    "qty":[10,5,7,3,2,9]
})
```

### Contoh Output
```
product     A   B  Grand Total
region
ID         12   7           19
MY          3   0            3
SG          5   0            5
Grand Total 20  7           27
```

### Hint
- Filter Q2: month in `[4,5,6]` & year `2025`
- Gunakan `pivot_table` atau `groupby(...).sum().unstack()`
- `fillna(0).astype(int)` untuk nol
- Tambah total baris & kolom dengan `sum(axis=1)` & `sum(axis=0)`


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "date": pd.to_datetime([
        "2025-04-01","2025-04-02","2025-05-15","2025-06-10",
        "2025-03-30","2025-07-01"
    ]),
    "region": ["ID","SG","ID","MY","ID","SG"],
    "product":["A","A","B","A","A","B"],
    "qty":[10,5,7,3,2,9]
})

 ## Jawaban disini ##

## 9. Mini ETL: Extract–Transform–Load
Topik: Modular function, parsing CSV sederhana, filter/sort

### Cerita
Kamu menerima data CSV sebagai string. Buat pipeline mini:
- extract: ubah CSV string → list of dict
- transform: filter price >= 100, tambah kolom amount = qty * price
- load: kembalikan list dict terurut dari amount terbesar ke kecil (ambil top-N)

### Contoh Input
```py
csv_text = """sku,qty,price
A1,2,120.5
B2,5,20
C3,1,300
D4,3,150
"""
top_n = 3
```

### Contoh Output
```
[
 {'sku': 'C3', 'qty': 1, 'price': 300.0, 'amount': 300.0},
 {'sku': 'D4', 'qty': 3, 'price': 150.0, 'amount': 450.0},
 {'sku': 'A1', 'qty': 2, 'price': 120.5, 'amount': 241.0}
]
```

### Hint
- `str.strip().splitlines()` untuk pecah baris
- Baris header → tentukan urutan kolom
- Casting tipe: `int()` dan `float()`
- `sorted(list, key=..., reverse=True)` untuk top-N


In [ ]:
def extract(csv_text):
     ## Jawaban disini ##

def transform(rows):
     ## Jawaban disini ##

def load(rows, top_n=3):
     ## Jawaban disini ##

# ---- run pipeline ----
csv_text = """sku,qty,price
A1,2,120.5
B2,5,20
C3,1,300
D4,3,150
"""
rows = extract(csv_text)
rows_t = transform(rows)
result = load(rows_t, top_n=3)
print(result)

## 10. Mini-Simulation OOP: Inventory Sederhana
Topik: OOP basic (class, attribute, method), validasi, operasi state

### Cerita
Buat sistem inventori sederhana:
- `add_item(name, qty)` → menambah stok
- `remove_item(name, qty)` → mengurangi stok (tidak boleh minus)
- `stock(name)` → cek stok item
- `low_stock(threshold)` → daftar item dengan stok ≤ threshold
Lalu proses **serangkaian operasi** dan tampilkan **stok akhir** serta **low stock**.

### Contoh Input
```py
ops = [
    ("add", "cable", 10),
    ("add", "adapter", 5),
    ("remove", "cable", 3),
    ("remove", "adapter", 7),  # gagal
    ("add", "adapter", 4),
]
threshold = 5
```

### Contoh Output
```
Final stock: {'cable': 7, 'adapter': 9}
Low stock (<=5): []
```
*(Jika data berbeda, daftar low stock bisa muncul.)*

### Hint
- Simpan stok pada dict `self._items`
- Validasi qty > 0
- `remove`: cek cukup stok; kalau tidak cukup → abaikan (return False)
- `low_stock`: loop dict dan ambil yang `qty <= threshold`


In [ ]:
class Inventory:
     ## Jawaban disini ##

# ---- run simulation ----
ops = [
    ("add", "cable", 10),
    ("add", "adapter", 5),
    ("remove", "cable", 3),
    ("remove", "adapter", 7),  # gagal
    ("add", "adapter", 4),
]
inv = Inventory()
for action, name, qty in ops:
    if action == "add":
        inv.add_item(name, qty)
    elif action == "remove":
        inv.remove_item(name, qty)

final_stock = dict(inv._items)
threshold = 5
print("Final stock:", final_stock)
print("Low stock (<=5):", inv.low_stock(threshold))

In [5]:
def access_elements(my_list):
    # Access and print the first element
    print(my_list[0])
    
    # Access and print the last element
    print(my_list[-1])

# Example list
example_list = [10, 20, 30, 40, 50]
access_elements(example_list)

# Expected Output:
# 10
# 50

10
50


In [11]:
# Travel Packing List and Selection
packing_list = ['clothes', 'toothbrush', 'passport', 'camera']
item_to_check = 'passport'

# TODO: Write a line of code to check if the item_to_check is in the packing_list
def check_item (item_to_check) :
    if item_to_check in packing_list :
        packing_list.index(item_to_check)
        print(f'{item_to_check} is in the {packing_list}')
    else :
        item_to_check[-1]
# TODO: Find the index of item_to_check in the list if it is packed, otherwise set it to -1

# Print out the results
check_item(item_to_check)
# print("Is the item packed?", is_item_packed)
# print("Item index:", item_index)

passport is in the ['clothes', 'toothbrush', 'passport', 'camera']


In [18]:
def are_you_playing_banjo(name):
    if name[0] == "R" or name[0] == "r" :
        return f'{name} plays banjo' 
    else :
        return f'{name} does not plat banjo'

print(are_you_playing_banjo('Ridho'))
print(are_you_playing_banjo('ridho'))
print(are_you_playing_banjo('Nexus'))

Ridho plays banjo
ridho plays banjo
Nexus does not plat banjo


In [17]:
name = "Ridho"
name[0]

'R'

In [24]:
def are_you_playing_banjo(name):
    if name[0] == "R" or name[0] == "r" :
        return f'{name} plays banjo' 
    else :
        return f'{name} does not play banjo'

print(are_you_playing_banjo('martin'))
print(are_you_playing_banjo('Rikke'))
print(are_you_playing_banjo('bravo'))
print(are_you_playing_banjo('rolf'))

martin does not play banjo
Rikke plays banjo
bravo does not play banjo
rolf plays banjo


In [39]:
# Initialize an empty list named 'suitcase'
suitcase = []
# TODO: Add items to your suitcase
new_item = ['baju', 'celana', 'topi']
suitcase.append(new_item)
print(suitcase)

# Declare a string variable for your goodbye message
gm = 'goodbye message'
# TODO: Assign a farewell message to the variable
farewell = gm

# Access the first and last item in your suitcase
# TODO: Print the first item in the suitcase
first_item = suitcase[0][0]
print(first_item)
# TODO: Print the last item in the suitcase
print(suitcase[0][-1])

# Send off with a farewell in uppercase
huruf_besar = farewell.upper()
# TODO: Print the farewell message in uppercase
print(huruf_besar)

[['baju', 'celana', 'topi']]
baju
topi
GOODBYE MESSAGE


In [35]:
nama = ['ridho','rasyid','muhammad']
nama[0]

'ridho'

In [ ]:
[True,  True,  True,  False,
  True,  True,  True,  True ,
  True,  False, True,  False,
  True,  False, False, True ,
  True,  True,  True,  True ,
  False, False, True,  True]

In [43]:
# Given mission name
mission_name = "Sort"

# TODO: Print the first and the last character of the mission name
print(mission_name[0])
print(mission_name[-1])

# TODO: The mission needs a minor update. We aim to change its first letter to 'P' and the last letter to `k`, obtaining the word "Pork".
first = mission_name.replace("S", "P")
print(first)
last = mission_name.replace("t", "k")
print(last)

# Remember, strings in Python are immutable, so you cannot alter them directly.

# TODO: Print the updated mission name
print(mission_name)

S
t
Port
Sork
Sort


In [2]:
numbers = [-5,-3,1,6,8,11]
target = 6

def get_index (target: int) :
    if target in numbers :
        return numbers.index(target)

get_index(target=6)

3

In [ ]:
# while loop
# while artinya → "ulangi selama kondisi masih benar (True)".
# Kalau kondisi berubah jadi False, loop berhenti.


# List of fruits to include in a fruit salad
fruits = ['apple', 'banana', 'orange', 'kiwi', 'melon']
fruit = 0 # index awal adalah 0

# Using a for loop to iterate over the list of fruits
while fruit <len(fruits): # loop terus berjalan selama index lebih kecil dari panjang list
    # Kalau len(fruits)=5, maka loop jalan saat index = 0,1,2,3,4.
    # selama index (fruit) masih lebih kecil dari jumlah item dalam list, lakukan loop”
    print(f"Adding {fruits[fruit]} to the salad.")
    fruit += 1 # tambahkan index pada setiap iterasi
    

Adding apple to the salad.
Adding banana to the salad.
Adding orange to the salad.
Adding kiwi to the salad.
Adding melon to the salad.


In [4]:
fruits = ['apple', 'banana', 'orange', 'kiwi', 'melon']


for fruit in fruits :
        print(f"Adding {fruit} to the salad.")

Adding apple to the salad.
Adding banana to the salad.
Adding orange to the salad.
Adding kiwi to the salad.
Adding melon to the salad.


In [15]:
my_list = ["apple", "banana", "cherry", "date"]
i = 0  # Initialize the index

while i < len(my_list):  # Loop while the index is within the list's bounds
    print(my_list[i])  # Access and print the element at the current index
    i += 1  # Increment the index for the next iteration

apple
banana
cherry
date


In [5]:
# List of fruits for the fruit salad
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
# Count the number of fruits in the salad
fruit_count = 0
# Loop over each fruit in the fruits list
for fruit in fruits:
    # The wrong operator is used here, it should increase the count
    fruit_count += 1
print(fruit_count)  # This should print the total number of fruits in the salad

5


In [22]:
def maps(a):
    return list(map(lambda x: x*2, a))

a = [1,2,3]
maps(a)

[2, 4, 6]

In [25]:
def checkOddEven(x):
    # code here
    if x % 2 == 0 :
        return f'Even'
    else :
        return f'Odd'

print(checkOddEven(4))

Even


In [26]:
def find_duplicates_with_seen_list(numbers):
    seen = []
    duplicates = []
    for num in numbers:
        if num in seen:
            if num not in duplicates:  # Avoid adding the same duplicate multiple times
                duplicates.append(num)
        else:
            seen.append(num)
    return duplicates

my_list = [1, 2, 3, 1, 2, 4, 5, 6, 5]
duplicate_numbers = find_duplicates_with_seen_list(my_list)
print(f"Duplicate numbers: {duplicate_numbers}")

Duplicate numbers: [1, 2, 5]


In [6]:
# List of fruits
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

i = 0                  # mulai dari index 0
result = ""            # string kosong untuk menampung hasil

# loop selama index belum melebihi jumlah buah
while i < len(fruits):
    if i == fruits[-1]:    
        # kalau index terakhir, tambahkan buah saja tanpa spasi
        result += fruits[i]
    else:
        # kalau bukan terakhir, tambahkan buah + spasi
        result += fruits[i] + " "
    i += 1  # geser index ke buah berikutnya

print(result)


apple banana cherry kiwi mango 


In [7]:
# List of fruits
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

i = 0                  # mulai dari index 0
result = ""            # string kosong untuk menampung hasil

# loop selama index belum melebihi jumlah buah
while i < len(fruits):
    if i == len(fruits) - 1:    
        # kalau index terakhir, tambahkan buah saja tanpa spasi
        result += fruits[i]
    else:
        # kalau bukan terakhir, tambahkan buah + spasi
        result += fruits[i] + " "
    i += 1  # geser index ke buah berikutnya

print(result)


apple banana cherry kiwi mango


In [8]:
# This code will create a simplified fruit salad with the provided fruits
fruits = ['apple', 'banana', 'cherry', 'date']
fruits_in_salad = ""

index = 0
# TODO: Create a while loop that assembles a string of fruit names separated by spaces, without adding a space after the last fruit
# Hint: Consider using a conditional to determine when to add a space
while index < len(fruits):
    if i == len(fruits) -1 :
        fruits_in_salad += fruits[index]
    else :
        fruits_in_salad += fruits[index] + " "
    index += 1
print(fruits_in_salad)  # Output the fruits in the salad

apple banana cherry date 


In [1]:
# This code will create a simplified fruit salad with the provided fruits
fruits = ['apple', 'banana', 'cherry', 'date']
fruits_in_salad = ""

index = 0
# TODO: Create a while loop that assembles a string of fruit names separated by spaces, without adding a space after the last fruit
# Hint: Consider using a conditional to determine when to add a space
while index < len(fruits):
    if index == len(fruits) -1 :
        fruits_in_salad += fruits[index]
    else :
        fruits_in_salad += fruits[index] + " "
    index += 1
print(fruits_in_salad)  # Output the fruits in the salad

apple banana cherry date


Dalam latihan ini, kamu diminta menghitung jumlah karakter yang bukan huruf vokal (a, e, i, o, u) dan juga bukan spasi (' ') pada sebuah string.

Jadi, setiap kali kamu menemukan huruf vokal atau spasi, karakter itu tidak dihitung.
Hanya huruf selain vokal dan spasi yang dihitung sebagai karakter non-vokal.

Apakah kamu ingin mencoba menghitungnya pada kata 'fruit salad'?

In [21]:
# Define a string named 'word' to represent the phrase we'll work with
word = 'FRUIT Salad'

# TODO: Initialize a counter to hold the number of non-vowel characters
vowels = 'aiueoAIUEO'

# TODO: Use a 'for' loop to iterate over each character in the string
result = ""
for v in word :
    if v not in vowels :
        result += v
print(result)
        

# TODO: Inside the loop, write a condition to check if it's not a vowel or a space
# Don't forget that letters can be lowercase and uppercase

# TODO: If the condition is true, increase the counter for non-vowel characters

# TODO: Finally, print out the count of non-vowel characters



FRT Sld
